# permissions for end users to edit backupdestinations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zomboid-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupdestination-editor-role
rules:
- apiGroups:
  - horde.host
  resources:
  - backupdestinations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - horde.host
  resources:
  - backupdestinations/status
  verbs:
  - get
