# permissions for end users to view zomboidservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zomboid-operator
    app.kubernetes.io/managed-by: kustomize
  name: zomboidserver-viewer-role
rules:
  - apiGroups:
      - horde.host
    resources:
      - zomboidservers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - horde.host
    resources:
      - zomboidservers/status
    verbs:
      - get
