# permissions for end users to edit zomboidbackupplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zomboid-operator
    app.kubernetes.io/managed-by: kustomize
  name: ZomboidBackupPlan-editor-role
rules:
  - apiGroups:
      - zomboid.host
    resources:
      - zomboidbackupplans
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - zomboid.host
    resources:
      - zomboidbackupplans/status
    verbs:
      - get
