apiVersion: v1
kind: Secret
metadata:
  name: zomboid-passwords
type: Opaque
stringData:
  admin-password: "tread with care"
  server-password: "let me in"
---
apiVersion: horde.host/v1
kind: ZomboidServer
metadata:
  name: zomboidserver-with-backups
spec:
  version: "41.78.16-20241106121439"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "1"
  storage:
    storageClassName: "standard"
    request: "2Gi"
    workshopRequest: "1Gi"
  backups:
    storageClassName: "standard"
    request: "2Gi"
  administrator:
    username: "admin"
    password:
      name: zomboid-passwords
      key: admin-password
  password:
    name: zomboid-passwords
    key: server-password
---
#
# S3
#
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  access-key: minioadmin
  secret-key: minioadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      initContainers:
        - name: init-bucket
          image: busybox:latest
          command:
            - mkdir
            - -p
            - /data/zomboid-backups
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secret-key
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
  selector:
    app: minio
---
apiVersion: horde.host/v1
kind: BackupDestination
metadata:
  name: s3-destination
spec:
  s3:
    bucketName: zomboid-backups
    endpoint: minio:9000
    endpointProtocol: "http"
    accessKeyId:
      name: minio-credentials
      key: access-key
    secretAccessKey:
      name: minio-credentials
      key: secret-key
---
apiVersion: horde.host/v1
kind: ZomboidBackupPlan
metadata:
  name: backup-my-server-to-s3
spec:
  server:
    name: zomboidserver-with-backups
  destination:
    name: s3-destination
  schedule: "0 0 * * *"
---
#
# Dropbox
#
apiVersion: horde.host/v1
kind: BackupDestination
metadata:
  name: dropbox-destination
spec:
  dropbox:
    remotePath: "/my/test/path"
    refreshToken:
      name: dropbox-token
      key: refresh-token
---
apiVersion: horde.host/v1
kind: ZomboidBackupPlan
metadata:
  name: backup-my-server-to-dropbox
spec:
  server:
    name: zomboidserver-with-backups
  destination:
    name: dropbox-destination
  schedule: "0 0 * * *"
