apiVersion: v1
kind: Secret
metadata:
  name: zomboid-passwords
type: Opaque
stringData:
  admin-password: "tread with care"
  server-password: "let me in"
---
apiVersion: zomboid.host/v1
kind: ZomboidServer
metadata:
  name: zomboidserver-sample
spec:
  version: "41.78.16-20241117211036"
  serverPort: 26261
  udpPort: 26262
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "1"
  storage:
    storageClassName: "standard"
    request: "2Gi"
  administrator:
    username: "admin"
    password:
      name: zomboid-passwords
      key: admin-password
  password:
    name: zomboid-passwords
    key: server-password
