apiVersion: v1
kind: Secret
metadata:
  name: zomboid-passwords
type: Opaque
stringData:
  admin-password: "tread with care"
  server-password: "let me in"
  user1-password: "its me"
  user2-password: "no it's me"
  bad-user-password: "i'm a griefer"
---
apiVersion: horde.host/v1
kind: ZomboidServer
metadata:
  name: zomboidserver-with-users
spec:
  version: "41.78.16-20241117211036"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "1"
  storage:
    storageClassName: "standard"
    request: "2Gi"
  administrator:
    username: "admin"
    password:
      name: zomboid-passwords
      key: admin-password
  password:
    name: zomboid-passwords
    key: server-password
  settings:
    player:
      Open: false
  users:
    - username: user1
      password:
        name: zomboid-passwords
        key: user1-password
    - username: user2
      password:
        name: zomboid-passwords
        key: user2-password
    - username: bad-user
      password:
        name: zomboid-passwords
        key: bad-user-password
---
apiVersion: v1
kind: Service
metadata:
  name: zomboidserver-with-users-game
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: zomboidserver-with-users
    app.kubernetes.io/managed-by: zomboid-operator
    app.kubernetes.io/name: zomboidserver
  ports:
    - name: steam
      port: 16261
      targetPort: 16261
      protocol: UDP
    - name: raknet
      port: 16262
      targetPort: 16262
      protocol: UDP
