apiVersion: v1
kind: Secret
metadata:
  name: zomboid-passwords
type: Opaque
stringData:
  admin-password: "tread with care"
  server-password: "let me in"
---
apiVersion: horde.host/v1
kind: ZomboidServer
metadata:
  name: zomboidserver-sample
spec:
  version: "41.78.16-20241106121439"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "1"
  storage:
    storageClassName: "standard"
    request: "2Gi"
  administrator:
    username: "admin"
    password:
      name: zomboid-passwords
      key: admin-password
  password:
    name: zomboid-passwords
    key: server-password
---
apiVersion: v1
kind: Service
metadata:
  name: zomboidserver-sample-game
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: zomboidserver-sample
    app.kubernetes.io/managed-by: zomboid-operator
    app.kubernetes.io/name: zomboidserver
  ports:
    - name: steam
      port: 16261
      targetPort: 16261
      protocol: UDP
    - name: raknet
      port: 16262
      targetPort: 16262
      protocol: UDP
