apiVersion: v1
kind: Secret
metadata:
  name: zomboid-admin
type: Opaque
stringData:
  password: "changeme"
---
apiVersion: horde.host/v1
kind: ZomboidServer
metadata:
  name: zomboidserver-sample
spec:
  version: "41.78.16"
  administrator:
    username: "admin"
    password:
      name: zomboid-admin
      key: password
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "1"
  storage:
    request: "10Gi"
