name: Image build
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/image.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/image.yaml"
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false
        required: false
      version:
        type: string
        required: false
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: zomboidhost
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=registry,ref=zomboidhost/zomboid-operator:buildcache
          cache-to: type=registry,ref=zomboidhost/zomboid-operator:buildcache,mode=max
          push: ${{ inputs.push || false }}
          tags: ${{ inputs.push && format('zomboidhost/zomboid-operator:latest,zomboidhost/zomboid-operator:{0}', inputs.version) || '' }}
