name: Release

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/unit-tests.yaml

  image:
    needs: test
    uses: ./.github/workflows/image.yaml
    with:
      push: true
      version: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  update-release:
    needs: image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "~1.23"
          cache: true

      - env:
          IMG: hordehost/zomboid-operator:${{ github.ref_name }}
        run: make build-installer

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/install.yaml
          asset_name: install.yaml
          asset_content_type: application/yaml
